# [M14] Magic Core Set 2014 pack generator

require './booster/default.rb'

class M14 < DefaultBooster
	def initialize
		mythic = [
			"Ajani, Caller of the Pride",
			"Archangel of Thune",
			"Devout Invocation",
			"Jace, Memory Adept",
			"Windreader Sphinx",
			"Liliana of the Dark Realms",
			"Rise of the Dark Realms",
			"Shadowborn Demon",
			"Chandra, Pyromaster",
			"Scourge of Valkas",
			"Garruk, Caller of Beasts",
			"Kalonian Hydra",
			"Primeval Bounty",
			"Darksteel Forge",
			"Ring of Three Wishes",
			]
		rare = [
			"Ajani's Chosen",
			"Imposing Sovereign",
			"Fiendslayer Paladin",
			"Planar Cleansing",
			"Silence",
			"Seraph of the Sword",
			"Indestructibility",
			"Bonescythe Sliver",
			"Path of Bravery",
			"Tidebinder Mage",
			"Galerider Sliver",
			"Domestication",
			"Clone",
			"Traumatize",
			"Jace's Mindseeker",
			"Elite Arcanist",
			"Quicken",
			"Colossal Whale",
			"Dismiss into Dream",
			"Lifebane Zombie",
			"Syphon Sliver",
			"Xathrid Necromancer",
			"Sanguine Bond",
			"Bogbrew Witch",
			"Grim Return",
			"Nightmare",
			"Dark Prophecy",
			"Liliana's Reaver",
			"Ogre Battledriver",
			"Goblin Diplomats",
			"Shivan Dragon",
			"Thorncaster Sliver",
			"Mindsparker",
			"Chandra's Phoenix",
			"Awaken the Ancient",
			"Burning Earth",
			"Wild Ricochet",
			"Scavenging Ooze",
			"Garruk's Horde",
			"Savage Summoning",
			"Vastwood Hydra",
			"Into the Wilds",
			"Oath of the Ancient Wood",
			"Megantic Sliver",
			"Witchstalker",
			"Door of Destinies",
			"Pyromancer's Gauntlet",
			"Trading Post",
			"Strionic Resonator",
			"Guardian of the Ages",
			"Ratchet Bomb",
			"Haunted Plate Mail",
			"Mutavault",
			]
		uncommon = [
			"Stonehorn Chanter",
			"Wall of Swords",
			"Steelform Sliver",
			"Blessing",
			"Brave the Elements",
			"Serra Angel",
			"Congregate",
			"Angelic Accord",
			"Banisher Priest",
			"Warden of Evos Isle",
			"Glimpse the Future",
			"Phantom Warrior",
			"Illusionary Armor",
			"Opportunity",
			"Wall of Frost",
			"Spell Blast",
			"Air Servant",
			"Water Servant",
			"Gnawing Zombie",
			"Vampire Warlord",
			"Artificer's Hex",
			"Blightcaster",
			"Tenacious Dead",
			"Sengir Vampire",
			"Corrupt",
			"Doom Blade",
			"Diabolic Tutor",
			"Flames of the Firebrand",
			"Shiv's Embrace",
			"Barrage of Expendables",
			"Battle Sliver",
			"Dragon Egg",
			"Fleshpulper Giant",
			"Volcanic Geyser",
			"Molten Birth",
			"Young Pyromancer",
			"Bramblecrush",
			"Briarpack Alpha",
			"Enlarge",
			"Kalonian Tusker",
			"Voracious Wurm",
			"Windstorm",
			"Manaweft Sliver",
			"Woodborn Behemoth",
			"Howl of the Night Pack",
			"Bubbling Cauldron",
			"Millstone",
			"Staff of the Death Magus",
			"Staff of the Mind Magus",
			"Darksteel Ingot",
			"Staff of the Sun Magus",
			"Accorder's Shield",
			"Vial of Poison",
			"Rod of Ruin",
			"Elixir of Immortality",
			"Fireshrieker",
			"Staff of the Flame Magus",
			"Staff of the Wild Magus",
			"Encroaching Wastes",
			"Shimmering Grotto",
			]
		common = [
			"Dawnstrike Paladin",
			"Auramancer",
			"Capashen Knight",
			"Griffin Sentinel",
			"Divine Favor",
			"Hive Stirrings",
			"Soulmender",
			"Celestial Flare",
			"Angelic Wall",
			"Charging Griffin",
			"Pillarfield Ox",
			"Show of Valor",
			"Pacifism",
			"Siege Mastodon",
			"Fortify",
			"Sentinel Sliver",
			"Solemn Offering",
			"Pay No Heed",
			"Suntail Hawk",
			"Master of Diversion",
			"Seacoast Drake",
			"Sensory Deprivation",
			"Trained Condor",
			"Archaeomancer",
			"Coral Merfolk",
			"Frost Breath",
			"Armored Cancrix",
			"Messenger Drake",
			"Time Ebb",
			"Cancel",
			"Zephyr Charge",
			"Nephalia Seakite",
			"Negate",
			"Tome Scour",
			"Disperse",
			"Claustrophobia",
			"Essence Scatter",
			"Merfolk Spy",
			"Scroll Thief",
			"Divination",
			"Undead Minotaur",
			"Shadowborn Apostle",
			"Mark of the Vampire",
			"Deathgaze Cockatrice",
			"Duress",
			"Shrivel",
			"Altar's Reap",
			"Corpse Hauler",
			"Mind Rot",
			"Festering Newt",
			"Blood Bairn",
			"Liturgy of Blood",
			"Quag Sickness",
			"Wring Flesh",
			"Accursed Spirit",
			"Vile Rebirth",
			"Minotaur Abomination",
			"Dark Favor",
			"Nightwing Shade",
			"Child of Night",
			"Academy Raider",
			"Lightning Talons",
			"Thunder Strike",
			"Canyon Minotaur",
			"Goblin Shortcutter",
			"Cyclops Tyrant",
			"Seismic Stomp",
			"Blur Sliver",
			"Shock",
			"Striking Sliver",
			"Chandra's Outrage",
			"Dragon Hatchling",
			"Demolish",
			"Act of Treason",
			"Marauding Maulhorn",
			"Pitchburn Devils",
			"Wild Guess",
			"Smelt",
			"Lava Axe",
			"Regathan Firecat",
			"Deadly Recluse",
			"Elvish Mystic",
			"Giant Spider",
			"Naturalize",
			"Giant Growth",
			"Advocate of the Beast",
			"Hunt the Weak",
			"Verdant Haven",
			"Plummet",
			"Lay of the Land",
			"Rumbling Baloth",
			"Trollhide",
			"Fog",
			"Sporemound",
			"Predatory Sliver",
			"Brindle Boar",
			"Groundshaker Sliver",
			"Gladecover Scout",
			"Rootwalla",
			"Ranger's Guile",
			"Sliver Construct",
			]
		basicland = [
			'Plains',
			'Plains',
			'Plains',
			'Plains',
			'Island',
			'Island',
			'Island',
			'Island',
			'Swamp',
			'Swamp',
			'Swamp',
			'Swamp',
			'Mountain',
			'Mountain',
			'Mountain',
			'Mountain',
			'Forest',
			'Forest',
			'Forest',
			'Forest',
			]
		super(mythic, rare, uncommon, common, basicland)
	end
end
