# [MMA] Modern Masters pack generator

class MMA
	def initialize
		@mythic = [
			'Elspeth, Knight Errant',
			'Yosei, the Morning Star',
			'Keiga, the Tide Star',
			'Vendilion Clique',
			'Dark Confidant',
			'Kokusho, the Evening Star',
			'Kiki-Jiki, Mirror Breaker',
			'Ryusei, the Falling Star',
			'Jugan, The Rising Star',
			'Tarmogoyf',
			'Progenitus',
			'Sarkhan Vol',
			'Sword of Fire and Ice',
			'Sword of Light and Shadow',
			'Vedalken Shackles',
			]
		@rare = [
			'Adarkar Valkyrie',
			'Angel\'s Grace',
			'Auriok Salvagers',
			'Ethersworn Canonist',
			'Kataki, War\'s Wage',
			'Reveillark',
			'Stonehewer Giant',
			'Cryptic Command',
			'Gifts Ungiven',
			'Glen Elendra Archmage',
			'Kira, Great Glass-Spinner',
			'Meloku the Clouded Mirror',
			'Pact of Negation',
			'Scion of Oona',
			'Bridge from Below',
			'Death Cloud',
			'Earwig Squad',
			'Extirpate',
			'Skeletal Vampire',
			'Slaughter Pact',
			'Tombstalker',
			'Blood Moon',
			'Countryside Crusher',
			'Dragonstorm',
			'Greater Gargadon',
			'Molten Disaster',
			'Pyromancer\'s Swath',
			'Squee, Goblin Nabob',
			'Doubling Season',
			'Life from the Loam',
			'Rude Awakening',
			'Summoner\'s Pact',
			'Tooth and Nail',
			'Verdeloth the Ancient',
			'Woodfall Primus',
			'Grand Arbiter Augustin IV',
			'Jhoira of the Ghitu',
			'Knight of the Reliquary',
			'Maelstrom Pulse',
			'Cold-Eyed Selkie',
			'Demigod of Revenge',
			'Divinity of Pride',
			'Figure of Destiny',
			'Oona, Queen of the Fae',
			'Aether Vial',
			'Arcbound Ravager',
			'Chalice of the Void',
			'Engineered Explosives',
			'Lotus Bloom',
			'Academy Ruins',
			'Blinkmoth Nexus',
			'City of Brass',
			'Glimmervoid',
			]
		@uncommon = [
			'Cloudgoat Ranger',
			'Feudkiller\'s Verdict',
			'Flickerwisp',
			'Meadowboon',
			'Path to Exile',
			'Sandsower',
			'Stir the Pride',
			'Terashi\'s Grasp',
			'Careful Consideration',
			'Esperzoa',
			'Mulldrifter',
			'Narcomoeba',
			'Riftwing Cloudskate',
			'Spell Snare',
			'Take Possession',
			'Thirst for Knowledge',
			'Auntie\'s Snitch',
			'Death Rattle',
			'Executioner\'s Capsule',
			'Horobi\'s Whisper',
			'Mad Auntie',
			'Marsh Flitter',
			'Phthisis',
			'Desperate Ritual',
			'Grinning Ignus',
			'Pardic Dragon',
			'Shrapnel Blast',
			'Sudden Shock',
			'Tar Pitcher',
			'Thundercloud Shaman',
			'Tribal Flames',
			'Eternal Witness',
			'Incremental Growth',
			'Krosan Grip',
			'Masked Admirers',
			'Reach of Branches',
			'Riftsweeper',
			'Sporesower Thallid',
			'Tromp the Domains ',
			'Electrolyze',
			'Lightning Helix',
			'Mind Funeral',
			'Tidehollow Sculler',
			'Trygon Predator',
			'Kitchen Finks',
			'Manamorphose',
			'Murderous Redcap',
			'Plumeveil',
			'Worm Harvest',
			'Epochrasite',
			'Etched Oracle',
			'Myr Retriever',
			'Paradise Mantle',
			'Relic of Progenitus',
			'Dakmor Salvage',
			'Vivid Crag',
			'Vivid Creek',
			'Vivid Grove',
			'Vivid Marsh',
			'Vivid Meadow',
			]
		@common = [
			'Amrou Scout',
			'Amrou Seekers',
			'Avian Changeling',
			'Blinding Beam',
			'Bound in Silence',
			'Cenn\'s Enlistment',
			'Court Homunculus',
			'Dispeller\'s Capsule',
			'Gleam of Resistance',
			'Hillcomber Giant',
			'Ivory Giant',
			'Kithkin Greatheart',
			'Otherworldly Journey',
			'Pallid Mycoderm',
			'Saltfield Recluse',
			'Sanctum Gargoyle',
			'Test of Faith',
			'Veteran Armorer',
			'Aethersnipe',
			'Dampen Thought',
			'Echoing Truth',
			'Errant Ephemeron',
			'Erratic Mutation',
			'Etherium Sculptor',
			'Faerie Mechanist',
			'Latchkey Faerie',
			'Logic Knot',
			'Mothdust Changeling',
			'Peer Through Depths',
			'Perilous Research',
			'Pestermite',
			'Petals of Insight',
			'Reach Through Mists',
			'Spellstutter Sprite',
			'Traumatic Visions',
			'Vedalken Dismisser',
			'Absorb Vis',
			'Blightspeaker',
			'Death Denied',
			'Deepcavern Imp',
			'Drag Down',
			'Dreamspoiler Witches',
			'Facevaulter',
			'Faerie Macabre',
			'Festering Goblin',
			'Peppersmoke',
			'Rathi Trapper',
			'Raven\'s Crime',
			'Stinkweed Imp',
			'Street Wraith',
			'Syphon Life',
			'Thieving Sprite',
			'Warren Pilferers',
			'Warren Weirding',
			'Blind-Spot Giant',
			'Brute Force',
			'Crush Underfoot',
			'Empty the Warrens',
			'Fiery Fall',
			'Fury Charm',
			'Glacial Ray',
			'Grapeshot',
			'Hammerheim Deadeye',
			'Lava Spike',
			'Mogg War Marshal',
			'Rift Bolt',
			'Rift Elemental',
			'Stingscourger',
			'Stinkdrinker Daredevil',
			'Thundering Giant',
			'Torrent of Stone',
			'War-Spike Changeling',
			'Citanul Woodreaders',
			'Durkwood Baloth',
			'Echoing Courage',
			'Giant Dustwasp',
			'Greater Mossdog',
			'Hana Kami',
			'Imperiosaur',
			'Kodama\'s Reach',
			'Moldervine Cloak',
			'Nantuko Shaman',
			'Penumbra Spider',
			'Search for Tomorrow',
			'Sporoloth Ancient',
			'Sylvan Bounty',
			'Thallid',
			'Thallid Germinator',
			'Thallid Shell-Dweller',
			'Walker of the Grove',
			'Aether Spellbomb',
			'Arcbound Stinger',
			'Arcbound Wanderer',
			'Arcbound Worker',
			'Bonesplitter',
			'Frogmite',
			'Myr Enforcer',
			'Pyrite Spellbomb',
			'Runed Stalactite',
			'Skyreach Manta',
			'Terramorphic Expanse',
			]
		@all = @mythic + @rare + @uncommon + @common
	end

	def generate
		mythic = rand(8) == 7
		a = mythic ? @mythic.shuffle[0..0] : @rare.shuffle[0..0]
		b = @uncommon.shuffle[0..2]
		c = @common.shuffle[0..9]
		d = @all.shuffle[0..0]
		a + b + c + d
	end
end
