# [MMA15] Modern Masters 2015 Edition pack generator

require './booster/default.rb'

class MMA15 < DefaultBooster
	def initialize
		mythic = [
                        'Emrakul, the Aeons Torn',
                        'Karn Liberated',
                        'Kozilek, Butcher of Truth',
                        'Ulamog, the Infinite Gyre',
                        'Elesh Norn, Grand Cenobite',
                        'Iona, Shield of Emeria',
                        'Tezzeret the Seeker',
                        'Vendilion Clique',
                        'Bitterblossom',
                        'Dark Confidant',
                        'Comet Storm',
                        'Kiki-Jiki, Mirror Breaker',
                        'Primeval Titan',
                        'Tarmogoyf',
                        'Mox Opal'
			]
		rare = [
                        'All Is Dust',
                        'Battlegrace Angel',
                        'Daybreak Coronet',
                        'Indomitable Archangel',
                        'Leyline of Sanctity',
                        'Mirran Crusader',
                        'Mirror Entity',
                        'Argent Sphinx',
                        'Cryptic Command',
                        'Guile',
                        "Hurkyl's Recall",
                        'Inexorable Tide',
                        'Surrakar Spellblade',
                        'Endrek Sahr, Master Breeder',
                        'Midnight Banshee',
                        'Necroskitter',
                        'Profane Command',
                        'Puppeteer Clique',
                        'Surgical Extraction',
                        'Banefire',
                        'Hellkite Charger',
                        'Spikeshot Elder',
                        'Splinter Twin',
                        'Thunderblust',
                        'Wildfire',
                        "All Suns' Dawn",
                        'Ant Queen',
                        'Noble Hierarch',
                        'Overwhelming Stampede',
                        'Scute Mob',
                        'Wolfbriar Elemental',
                        'Apocalypse Hydra',
                        'Creakwood Liege',
                        'Fulminator Mage',
                        'Ghost Council of Orzhova',
                        'Horde of Notions',
                        'Mystic Snake',
                        'Niv-Mizzet, the Firemind',
                        'Nobilis of War',
                        'Shadowmage Infiltrator',
                        'Swans of Bryn Argoll',
                        'Wilt-Leaf Liege',
                        'Chimeric Mass',
                        'Etched Champion',
                        'Etched Monstrosity',
                        'Lodestone Golem',
                        'Lodestone Myr',
                        'Long-Forgotten Gohei',
                        'Precursor Golem',
                        'Spellskite',
                        'Sunforger',
                        'Blinkmoth Nexus',
                        'Eye of Ugin'
			]
		uncommon = [
                        'Artisan of Kozilek',
                        'Celestial Purge',
                        'Dispatch',
                        'Hikari, Twilight Guardian',
                        'Kor Duelist',
                        'Myrsmith',
                        'Oblivion Ring',
                        'Spectral Procession',
                        'Taj-Nar Swordsmith',
                        'Air Servant',
                        'Flashfreeze',
                        'Mulldrifter',
                        'Novijen Sages',
                        'Qumulox',
                        'Remand',
                        "Tezzeret's Gambit",
                        'Water Servant',
                        'Daggerclaw Imp',
                        'Deathmark',
                        'Devouring Greed',
                        'Dismember',
                        'Reassembling Skeleton',
                        'Scavenger Drake',
                        'Spread the Sickness',
                        'Vampire Outcasts',
                        'Bloodshot Trainee',
                        'Combust',
                        'Incandescent Soulstoke',
                        'Lightning Bolt',
                        'Skarrgan Firebird',
                        'Spitebellows',
                        'Stormblood Berserker',
                        'Worldheart Phoenix',
                        'Algae Gharial',
                        'Bestial Menace',
                        'Cytoplast Root-Kin',
                        'Karplusan Strider',
                        'Mutagenic Growth',
                        'Overwhelm',
                        'Pelakka Wurm',
                        'Root-Kin Ally',
                        'Agony Warp',
                        'Ashenmoor Gouger',
                        'Boros Swiftblade',
                        'Dimir Guildmage',
                        'Drooling Groodion',
                        'Electrolyze',
                        'Ethercaste Knight',
                        'Glassdust Hulk',
                        'Hearthfire Hobgoblin',
                        'Lorescale Coatl',
                        'Necrogenesis',
                        'Pillory of the Sleepless',
                        'Plaxcaster Frogling',
                        'Restless Apparition',
                        'Savage Twister',
                        'Selesnya Guildmage',
                        'Shrewd Hatchling',
                        'Sigil Blessing',
                        'Vengeful Rebirth',
                        'Wrecking Ball',
                        'Cranial Plating',
                        'Culling Dais',
                        'Darksteel Axe',
                        'Etched Oracle',
                        'Everflowing Chalice',
                        'Expedition Map',
                        'Mortarpod',
                        'Tumble Magnet',
                        'Azorius Chancery',
                        'Boros Garrison',
                        'Dimir Aqueduct',
                        'Eldrazi Temple',
                        'Golgari Rot Farm',
                        'Gruul Turf',
                        'Izzet Boilerworks',
                        'Orzhov Basilica',
                        'Rakdos Carnarium',
                        'Selesnya Sanctuary',
                        'Simic Growth Chamber'
			]
		common = [
                        "Ulamog's Crusher",
                        "Apostle's Blessing",
                        'Arrest',
                        'Conclave Phalanx',
                        'Court Homunculus',
                        'Fortify',
                        'Kami of Ancient Law',
                        'Mighty Leap',
                        'Moonlit Strider',
                        'Otherworldly Journey',
                        'Raise the Alarm',
                        'Skyhunter Skirmisher',
                        'Sunlance',
                        'Sunspear Shikari',
                        "Terashi's Grasp",
                        'Waxmane Baku',
                        'Æthersnipe',
                        'Cloud Elemental',
                        'Faerie Mechanist',
                        'Helium Squirter',
                        'Mana Leak',
                        'Narcolepsy',
                        'Repeal',
                        'Somber Hoverguard',
                        'Steady Progress',
                        'Stoic Rebuttal',
                        'Telling Time',
                        'Thoughtcast',
                        'Thrummingbird',
                        'Vapor Snag',
                        'Vigean Graftmage',
                        'Wings of Velis Vel',
                        'Bloodthrone Vampire',
                        'Bone Splinters',
                        'Death Denied',
                        'Dread Drone',
                        'Duskhunter Bat',
                        'Ghostly Changeling',
                        'Grim Affliction',
                        'Instill Infection',
                        'Nameless Inversion',
                        'Plagued Rusalka',
                        'Scuttling Death',
                        'Shrivel',
                        'Sickle Ripper',
                        'Sign in Blood',
                        'Thief of Hope',
                        'Vampire Lacerator',
                        'Waking Nightmare',
                        'Blades of Velis Vel',
                        'Blood Ogre',
                        'Brute Force',
                        'Burst Lightning',
                        'Dragonsoul Knight',
                        'Fiery Fall',
                        'Goblin Fireslinger',
                        'Goblin War Paint',
                        'Gorehorn Minotaurs',
                        'Gut Shot',
                        'Inner-Flame Igniter',
                        'Smash to Smithereens',
                        'Smokebraider',
                        'Soulbright Flamekin',
                        'Tribal Flames',
                        'Viashino Slaughtermaster',
                        'Wrap in Flames',
                        'Aquastrand Spider',
                        'Commune with Nature',
                        'Gnarlid Pack',
                        'Kavu Primarch',
                        'Kozilek’s Predator',
                        'Matca Rioters',
                        'Nest Invader',
                        'Plummet',
                        'Rampant Growth',
                        'Scatter the Seeds',
                        'Scion of the Wild',
                        'Simic Initiate',
                        'Sundering Vitae',
                        'Sylvan Bounty',
                        'Thrive',
                        'Tukatongue Thallid',
                        'Vines of Vastwood',
                        'Alloy Myr',
                        'Blinding Souleater',
                        'Cathodion',
                        'Copper Carapace',
                        'Flayer Husk',
                        'Frogmite',
                        'Glint Hawk Idol',
                        'Gust-Skimmer',
                        'Kitesail',
                        'Myr Enforcer',
                        'Runed Servitor',
                        'Rusted Relic',
                        'Sickleslicer',
                        'Skyreach Manta',
                        'Sphere of the Suns',
                        'Wayfarer’s Bauble'
			]
		basicland = [
			'Plains',
			'Plains',
			'Plains',
			'Plains',
			'Island',
			'Island',
			'Island',
			'Island',
			'Swamp',
			'Swamp',
			'Swamp',
			'Swamp',
			'Mountain',
			'Mountain',
			'Mountain',
			'Mountain',
			'Forest',
			'Forest',
			'Forest',
			'Forest',
			]
		super(mythic, rare, uncommon, common, basicland)
	end
end
