# Magic Online Cube (2013-5-1 ~ 2013-5-8)

class MOCube
	def initialize
		@pool = [
			# White
			'Porcelain Legionnaire',
			'Academy Rector',
			'Akroma, Angel of Wrath',
			'Angel of Serenity',
			'Aven Mindcensor',
			'Baneslayer Angel',
			'Blade Splicer',
			'Calciderm',
			'Cloudgoat Ranger',
			'Descendant of Kiyomaro',
			'Eight-and-a-Half-Tails',
			'Elesh Norn, Grand Cenobite',
			'Elite Vanguard',
			'Emeria Angel',
			'Exalted Angel',
			'Fiend Hunter',
			'Flickerwisp',
			'Hand of Honor',
			'Hero of Bladehold',
			'Hokori, Dust Drinker',
			'Iona, Shield of Emeria',
			'Isamaru, Hound of Konda',
			'Jotun Grunt',
			'Kami of Ancient Law',
			'Knight of Glory',
			'Knight of the White Orchid',
			'Leonin Relic-Warder',
			'Linvala, Keeper of Silence',
			'Loam Lion',
			'Mentor of the Meek',
			'Mirran Crusader',
			'Mirror Entity',
			'Mother of Runes',
			'Nearheath Pilgrim',
			'Paladin en-Vec',
			'Pristine Angel',
			'Ranger of Eos',
			'Restoration Angel',
			'Reveillark',
			'Ronom Unicorn',
			'Savannah Lions',
			'Shrieking Grotesque',
			'Silver Knight',
			'Silverblade Paladin',
			'Steppe Lynx',
			'Stonecloaker',
			'Stoneforge Mystic',
			'Student of Warfare',
			'Sublime Archangel',
			'Sun Titan',
			'Thalia, Guardian of Thraben',
			'Wall of Omens',
			'Wall of Reverence',
			'Weathered Wayfarer',
			'Whipcorder',
			'Yosei, the Morning Star',
			'Angelic Destiny',
			'Faith\'s Fetters',
			'Glorious Anthem',
			'Honor of the Pure',
			'Journey to Nowhere',
			'Land Tax',
			'Oblivion Ring',
			'Parallax Wave',
			'Seal of Cleansing',
			'Condemn',
			'Disenchant',
			'Dismantling Blow',
			'Enlightened Tutor',
			'Mana Tithe',
			'Momentary Blink',
			'Path to Exile',
			'Shining Shoal',
			'Swords to Plowshares',
			'Tithe',
			'Ajani Goldmane',
			'Ajani, Caller of the Pride',
			'Elspeth Tirel',
			'Elspeth, Knight-Errant',
			'Gideon Jura',
			'Gideon, Champion of Justice',
			'Akroma\'s Vengeance',
			'Armageddon',
			'Balance',
			'Cataclysm',
			'Catastrophe',
			'Celestial Purge',
			'Day of Judgment',
			'Decree of Justice',
			'Entreat the Angels',
			'Hallowed Burial',
			'Lingering Souls',
			'Martial Coup',
			'Oust',
			'Ravages of War',
			'Rout',
			'Spectral Procession',
			'Terminus',
			'Wrath of God',
			# Blue
			'Phyrexian Metamorph',
			'Augur of Bolas',
			'Consecrated Sphinx',
			'Coralhelm Commander',
			'Court Hussar',
			'Cursecatcher',
			'Delver of Secrets',
			'Dungeon Geists',
			'Enclave Cryptologist',
			'Fathom Seer',
			'Frost Titan',
			'Glen Elendra Archmage',
			'Jushi Apprentice',
			'Keiga, the Tide Star',
			'Kira, Great Glass-Spinner',
			'Looter il-Kor',
			'Man-o\'-War',
			'Meloku the Clouded Mirror',
			'Mulldrifter',
			'Ninja of the Deep Hours',
			'Old Man of the Sea',
			'Palinchron',
			'Phantasmal Bear',
			'Phantasmal Image',
			'Riftwing Cloudskate',
			'Sakashima\'s Student',
			'Sea Gate Oracle',
			'Serendib Efreet',
			'Snapcaster Mage',
			'Sower of Temptation',
			'Sphinx of Jwar Isle',
			'Talrand, Sky Summoner',
			'Teferi, Mage of Zhalfir',
			'Thieving Magpie',
			'Tradewind Rider',
			'Trinket Mage',
			'Vendilion Clique',
			'Venser, Shaper Savant',
			'Vesuvan Shapeshifter',
			'Voidmage Prodigy',
			'Wake Thrasher',
			'Willbender',
			'Control Magic',
			'Future Sight',
			'Legacy\'s Allure',
			'Narcolepsy',
			'Opposition',
			'Spreading Seas',
			'Treachery',
			'Blue Elemental Blast',
			'Brain Freeze',
			'Brainstorm',
			'Capsize',
			'Condescend',
			'Counterspell',
			'Cryptic Command',
			'Daze',
			'Dismiss',
			'Dissipate',
			'Essence Scatter',
			'Fact or Fiction',
			'Flashfreeze',
			'Forbid',
			'Forbidden Alchemy',
			'Force of Will',
			'Force Spike',
			'Frantic Search',
			'Gifts Ungiven',
			'Hinder',
			'Impulse',
			'Into the Roil',
			'Mana Leak',
			'Miscalculation',
			'Misdirection',
			'Mystical Tutor',
			'Negate',
			'Pact of Negation',
			'Remand',
			'Repeal',
			'Spell Pierce',
			'Thirst for Knowledge',
			'Turnabout',
			'Jace Beleren',
			'Jace, Architect of Thought',
			'Jace, the Mind Sculptor',
			'Tamiyo, the Moon Sage',
			'Ancestral Vision',
			'Compulsive Research',
			'Deep Analysis',
			'Mind\'s Desire',
			'Ponder',
			'Preordain',
			'Serum Visions',
			'Show and Tell',
			'Tidings',
			'Time Spiral',
			'Time Warp',
			'Tinker',
			'Upheaval',
			# Black
			'Bane of the Living',
			'Bloodghast',
			'Bloodgift Demon',
			'Bloodline Keeper',
			'Bone Shredder',
			'Braids, Cabal Minion',
			'Carnophage',
			'Dark Confidant',
			'Diregraf Ghoul',
			'Gatekeeper of Malakir',
			'Geralf\'s Messenger',
			'Grave Titan',
			'Graveborn Muse',
			'Gravecrawler',
			'Griselbrand',
			'Guul Draz Assassin',
			'Hand of Cruelty',
			'Headhunter',
			'Hypnotic Specter',
			'Ink-Eyes, Servant of Oni',
			'Knight of Infamy',
			'Kokusho, the Evening Star',
			'Korlash, Heir to Blackblade',
			'Mesmeric Fiend',
			'Nantuko Shade',
			'Nekrataal',
			'Nezumi Graverobber',
			'Nezumi Shortfang',
			'Nightscape Familiar',
			'Okiba-Gang Shinobi',
			'Oona\'s Prowler',
			'Phyrexian Obliterator',
			'Phyrexian Rager',
			'Plague Sliver',
			'Putrid Imp',
			'Ravenous Rats',
			'Shriekmaw',
			'Silent Specter',
			'Skeletal Vampire',
			'Skinrender',
			'Tombstalker',
			'Undead Gladiator',
			'Vampire Hexmage',
			'Vampire Lacerator',
			'Vampire Nighthawk',
			'Visara the Dreadful',
			'Animate Dead',
			'Attrition',
			'Bitterblossom',
			'Diabolic Servitude',
			'Necromancy',
			'Necropotence',
			'Phyrexian Arena',
			'Recurring Nightmare',
			'Sarcomancy',
			'Dark Ritual',
			'Disfigure',
			'Dismember',
			'Doom Blade',
			'Entomb',
			'Exhume',
			'Go for the Throat',
			'Makeshift Mannequin',
			'Skeletal Scrying',
			'Slaughter Pact',
			'Smother',
			'Snuff Out',
			'Sorin\'s Thirst',
			'Spinning Darkness',
			'Tainted Pact',
			'Tendrils of Corruption',
			'Tragic Slip',
			'Ultimate Price',
			'Vampiric Tutor',
			'Liliana of the Veil',
			'Liliana Vess',
			'Black Sun\'s Zenith',
			'Buried Alive',
			'Chainer\'s Edict',
			'Corrupt',
			'Damnation',
			'Death Cloud',
			'Demonic Tutor',
			'Duress',
			'Hymn to Tourach',
			'Inquisition of Kozilek',
			'Living Death',
			'Night\'s Whisper',
			'Persecute',
			'Profane Command',
			'Reanimate',
			'Sign in Blood',
			'Sinkhole',
			'Stupor',
			'Tendrils of Agony',
			'Thoughtseize',
			'Unburial Rites',
			'Wrench Mind',
			'Yawgmoth\'s Will',
			# Red
			'Ash Zealot',
			'Avalanche Riders',
			'Ball Lightning',
			'Blistering Firecat',
			'Bogardan Hellkite',
			'Chandra\'s Phoenix',
			'Countryside Crusher',
			'Cunning Sparkmage',
			'Ember Hauler',
			'Flametongue Kavu',
			'Frenzied Goblin',
			'Gathan Raiders',
			'Goblin Cadets',
			'Goblin Guide',
			'Goblin Patrol',
			'Goblin Ruinblaster',
			'Goblin Welder',
			'Gore-House Chainwalker',
			'Greater Gargadon',
			'Grim Lavamancer',
			'Hell\'s Thunder',
			'Hellrider',
			'Hellspark Elemental',
			'Hero of Oxid Ridge',
			'Inferno Titan',
			'Jackal Pup',
			'Kargan Dragonlord',
			'Keldon Champion',
			'Keldon Marauders',
			'Kird Ape',
			'Lightning Mauler',
			'Magus of the Moon',
			'Mogg War Marshal',
			'Orcish Lumberjack',
			'Plated Geopede',
			'Priest of Urabrask',
			'Ravenous Baboons',
			'Siege-Gang Commander',
			'Spikeshot Elder',
			'Stormblood Berserker',
			'Stromkirk Noble',
			'Taurean Mauler',
			'Thunderblust',
			'Thundermaw Hellkite',
			'Thunderscape Battlemage',
			'Tin Street Hooligan',
			'Torch Fiend',
			'Urabrask the Hidden',
			'Zealous Conscripts',
			'Zo-Zu the Punisher',
			'Genju of the Spires',
			'Sneak Attack',
			'Sulfuric Vortex',
			'Ancient Grudge',
			'Brimstone Volley',
			'Burst Lightning',
			'Chaos Warp',
			'Char',
			'Desperate Ravings',
			'Fireblast',
			'Firestorm',
			'Flame Javelin',
			'Incinerate',
			'Lightning Bolt',
			'Magma Jet',
			'Price of Progress',
			'Red Elemental Blast',
			'Searing Blaze',
			'Seething Song',
			'Skullcrack',
			'Smash to Smithereens',
			'Staggershock',
			'Volcanic Fallout',
			'Chandra, the Firebrand',
			'Koth of the Hammer',
			'Arc Trail',
			'Banefire',
			'Bonfire of the Damned',
			'Burning of Xinye',
			'Chain Lightning',
			'Destructive Force',
			'Devil\'s Play',
			'Earthquake',
			'Empty the Warrens',
			'Faithless Looting',
			'Firebolt',
			'Forked Bolt',
			'Gamble',
			'Mark of Mutiny',
			'Mizzium Mortars',
			'Molten Rain',
			'Pillage',
			'Pyroclasm',
			'Reckless Charge',
			'Rift Bolt',
			'Rolling Earthquake',
			'Slagstorm',
			'Wheel of Fortune',
			'Wildfire',
			# Green
			'Birthing Pod',
			'Acidic Slime',
			'Arbor Elf',
			'Avacyn\'s Pilgrim',
			'Avenger of Zendikar',
			'Birds of Paradise',
			'Blastoderm',
			'Borderland Ranger',
			'Boreal Druid',
			'Brooding Saurian',
			'Civic Wayfinder',
			'Deranged Hermit',
			'Devoted Druid',
			'Dryad Sophisticate',
			'Elves of Deep Shadow',
			'Eternal Witness',
			'Experiment One',
			'Fauna Shaman',
			'Flinthoof Boar',
			'Fyndhorn Elves',
			'Genesis',
			'Great Sable Stag',
			'Hystrodon',
			'Indrik Stomphowler',
			'Joraga Treespeaker',
			'Llanowar Elves',
			'Lotus Cobra',
			'Master of the Wild Hunt',
			'Mold Shambler',
			'Nantuko Vigilante',
			'Noble Hierarch',
			'Obstinate Baloth',
			'Ohran Viper',
			'Oracle of Mul Daya',
			'Primeval Titan',
			'Rofellos, Llanowar Emissary',
			'Sakura-Tribe Elder',
			'Scavenging Ooze',
			'Strangleroot Geist',
			'Tarmogoyf',
			'Terastodon',
			'Thelonite Hermit',
			'Thornscape Battlemage',
			'Thragtusk',
			'Thrun, the Last Troll',
			'Troll Ascetic',
			'Ulvenwald Tracker',
			'Vengevine',
			'Wall of Blossoms',
			'Wall of Roots',
			'Wickerbough Elder',
			'Wild Nacatl',
			'Wolfir Silverheart',
			'Wood Elves',
			'Woodfall Primus',
			'Yavimaya Elder',
			'Yeva, Nature\'s Herald',
			'Awakening Zone',
			'Exploration',
			'Fertile Ground',
			'Heartbeat of Spring',
			'Rancor',
			'Survival of the Fittest',
			'Sylvan Library',
			'Beast Within',
			'Chord of Calling',
			'Krosan Grip',
			'Moment\'s Peace',
			'Naturalize',
			'Nature\'s Claim',
			'Vines of Vastwood',
			'Garruk Relentless',
			'Garruk Wildspeaker',
			'Garruk, Primal Hunter',
			'All Suns\' Dawn',
			'Call of the Herd',
			'Channel',
			'Cultivate',
			'Edge of Autumn',
			'Eureka',
			'Explore',
			'Farseek',
			'Genesis Wave',
			'Green Sun\'s Zenith',
			'Harmonize',
			'Kodama\'s Reach',
			'Life from the Loam',
			'Natural Order',
			'Nature\'s Lore',
			'Nostalgic Dreams',
			'Plow Under',
			'Primal Command',
			'Rampant Growth',
			'Regrowth',
			'Restock',
			'Rude Awakening',
			'Search for Tomorrow',
			'Stunted Growth',
			'Tooth and Nail',
			# Multicolored
			'Behemoth Sledge',
			'Baleful Strix',
			'Shardless Agent',
			'Bloodbraid Elf',
			'Broodmate Dragon',
			'Edric, Spymaster of Trest',
			'Falkenrath Aristocrat',
			'Figure of Destiny',
			'Gaddock Teeg',
			'Geist of Saint Traft',
			'Giant Solifuge',
			'Huntmaster of the Fells',
			'Kitchen Finks',
			'Mystic Snake',
			'Nightveil Specter',
			'Niv-Mizzet, Dracogenius',
			'Obzedat, Ghost Council',
			'Progenitus',
			'Putrid Leech',
			'Qasali Pridemage',
			'Rakdos Cackler',
			'Shadowmage Infiltrator',
			'Simic Sky Swallower',
			'Stillmoon Cavalier',
			'Trygon Predator',
			'Woolly Thoctar',
			'Detention Sphere',
			'Mirari\'s Wake',
			'Pernicious Deed',
			'Abrupt Decay',
			'Absorb',
			'Aurelia\'s Fury',
			'Bant Charm',
			'Boros Charm',
			'Dimir Charm',
			'Electrolyze',
			'Esper Charm',
			'Fire_Ice',
			'Izzet Charm',
			'Lightning Helix',
			'Prophetic Bolt',
			'Putrefy',
			'Sphinx\'s Revelation',
			'Terminate',
			'Undermine',
			'Ajani Vengeant',
			'Domri Rade',
			'Nicol Bolas, Planeswalker',
			'Sorin, Lord of Innistrad',
			'Blightning',
			'Dreadbore',
			'Firespout',
			'Maelstrom Pulse',
			'Merciless Eviction',
			'Supreme Verdict',
			'Vindicate',
			# Colorless
			'Emrakul, the Aeons Torn',
			'Kozilek, Butcher of Truth',
			'Ulamog, the Infinite Gyre',
			'Karn Liberated',
			'All Is Dust',
			# Artifact
			'Aether Vial',
			'Basalt Monolith',
			'Batterskull',
			'Bonesplitter',
			'Chrome Mox',
			'Coalition Relic',
			'Crucible of Worlds',
			'Cursed Scroll',
			'Elixir of Immortality',
			'Engineered Explosives',
			'Everflowing Chalice',
			'Gilded Lotus',
			'Grim Monolith',
			'Lion\'s Eye Diamond',
			'Lotus Bloom',
			'Manriki-Gusari',
			'Memory Jar',
			'Mind Stone',
			'Mox Diamond',
			'Nevinyrral\'s Disk',
			'Oblivion Stone',
			'Pithing Needle',
			'Powder Keg',
			'Pristine Talisman',
			'Ratchet Bomb',
			'Relic of Progenitus',
			'Scroll Rack',
			'Sensei\'s Divining Top',
			'Shrine of Burning Rage',
			'Skullclamp',
			'Smokestack',
			'Sphere of the Suns',
			'Sword of Body and Mind',
			'Sword of Fire and Ice',
			'Sword of War and Peace',
			'Tangle Wire',
			'Thran Dynamo',
			'Umezawa\'s Jitte',
			'Vedalken Shackles',
			'Winter Orb',
			'Worn Powerstone',
			'Epochrasite',
			'Etched Oracle',
			'Lodestone Golem',
			'Molten-Tail Masticore',
			'Myr Battlesphere',
			'Palladium Myr',
			'Phyrexian Revoker',
			'Precursor Golem',
			'Solemn Simulacrum',
			'Spellskite',
			'Sundering Titan',
			'Wurmcoil Engine',
			# Land
			'Academy Ruins',
			'Adarkar Wastes',
			'Ancient Tomb',
			'Arcane Sanctum',
			'Arid Mesa',
			'Azorius Chancery',
			'Bad River',
			'Badlands',
			'Barbarian Ring',
			'Battlefield Forge',
			'Bayou',
			'Blood Crypt',
			'Bloodstained Mire',
			'Boros Garrison',
			'Breeding Pool',
			'Brushland',
			'Cascade Bluffs',
			'Caves of Koilos',
			'Celestial Colonnade',
			'City of Brass',
			'Clifftop Retreat',
			'Creeping Tar Pit',
			'Crumbling Necropolis',
			'Dimir Aqueduct',
			'Dragonskull Summit',
			'Drowned Catacomb',
			'Faerie Conclave',
			'Fetid Heath',
			'Fire-Lit Thicket',
			'Flagstones of Trokair',
			'Flood Plain',
			'Flooded Grove',
			'Flooded Strand',
			'Gaea\'s Cradle',
			'Ghitu Encampment',
			'Glacial Fortress',
			'Godless Shrine',
			'Golgari Rot Farm',
			'Grasslands',
			'Graven Cairns',
			'Gruul Turf',
			'Halimar Depths',
			'Hallowed Fountain',
			'Hinterland Harbor',
			'Isolated Chapel',
			'Izzet Boilerworks',
			'Jungle Shrine',
			'Karakas',
			'Karplusan Forest',
			'Lake of the Dead',
			'Lavaclaw Reaches',
			'Llanowar Wastes',
			'Marsh Flats',
			'Maze of Ith',
			'Mishra\'s Factory',
			'Misty Rainforest',
			'Mountain Valley',
			'Murmuring Bosk',
			'Mutavault',
			'Mystic Gate',
			'Orzhov Basilica',
			'Overgrown Tomb',
			'Plateau',
			'Polluted Delta',
			'Raging Ravine',
			'Rakdos Carnarium',
			'Reflecting Pool',
			'Rishadan Port',
			'Rocky Tar Pit',
			'Rootbound Crag',
			'Rugged Prairie',
			'Sacred Foundry',
			'Savage Lands',
			'Savannah',
			'Scalding Tarn',
			'Scrubland',
			'Seaside Citadel',
			'Selesnya Sanctuary',
			'Shivan Reef',
			'Simic Growth Chamber',
			'Steam Vents',
			'Stirring Wildwood',
			'Stomping Ground',
			'Strip Mine',
			'Sulfur Falls',
			'Sulfurous Springs',
			'Sunken Ruins',
			'Sunpetal Grove',
			'Taiga',
			'Tectonic Edge',
			'Teetering Peaks',
			'Temple Garden',
			'Thawing Glaciers',
			'Treetop Village',
			'Tropical Island',
			'Tundra',
			'Twilight Mire',
			'Underground River',
			'Underground Sea',
			'Urborg, Tomb of Yawgmoth',
			'Verdant Catacombs',
			'Volcanic Island',
			'Volrath\'s Stronghold',
			'Wasteland',
			'Watery Grave',
			'Windbrisk Heights',
			'Windswept Heath',
			'Wooded Bastion',
			'Wooded Foothills',
			'Woodland Cemetery',
			'Yavimaya Coast',
			]
	end

	def generate(n)
		@pool.shuffle.each_slice(15).to_a[0...n]
	end
end
